# numpy(numerical python)

#### https://numpy.org

조밀한 데이터 버퍼에서 저장하고 처리하는 효과적인 인터페이스를 제공   
numpy 배열은 파이썬의 내장 타입인 list와 비슷하지만 배열의 규모가 커질수록 데이터 저장 및 처리에서 훨씬 더 효율적이다.   
numpy 배열은 파이썬의 데이터 과학 도구로 구성된 전체 생태계의 핵심을 이루고 있다.   
   
파이썬 데이터 과학도구 생태계   
numpy: 배열 표현   
pandas: 데이터 처리   
matplotlib: 시각화 처리   

API-함수 형태   
application   
programming   
interface-연결점, 통로.    
   
어떤 프로그래밍을 하는데 있어서 접근할 수 있는 통로 역할을 하는 것을 api라고 함.   

### numpy를 사용하기 위헤서는 import문을 통해 numpy를 import 한다.

In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.1'

### numpy 배열과 파이썬 배열의 비교

파이썬은 데이터를 효율적인 고정타입 데이터 버퍼에 저장하는 다양한 방식을 제공   
내장 array 모듈은 단일 타입의 조밀한 배열(dense array)을 만드는데 사용할 수 있다.   
array: 동일한 자료형의 집합. 1차원 배열은 vector(혹은 0차원), 2차원 배열을 matrix(1차원). 값은 scalar라고 부름.   

In [5]:
import array

In [6]:
L=list(range(10))
a=array.array('i',L)
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

-array는 기존의 list보다 동일 자료형을 저장하는 배열이므로 속도가 빠르다.   
-array보다 더 유용한 배열은 numpy 모듈의 nadarray 객체이다.   
-파이썬의 array객체는 배열 기반의 데이터에 효율적인 저장소를 제공하는 반면, numpy는 그 데이터의 효율적인 연산을 추가한다.   

In [7]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

-파이썬 리스트와 달리 numpy는 배열의 모든 요소가 같은 타입이어야 한다.   
-타입이 일치하지 않으면 numpy는 가능한 경우 상위 타입으로 변환하여 저장한다.   
   
ary1,2,3,4,5   
ary*2   
for i in ranget(5)   
ary[i]*2   

In [9]:
np.array([3.14, 4, 2.3])

array([3.14, 4.  , 2.3 ])

-파이썬 list는 다댱한 자료형을 저장하는 배열   
-파이썬 array는 동일한 자료형을 저장하는 배열   
-numpy ndarray는 동일한 자료형을 저장하는 배열(배열에 대한 연산이 포함)   
(import numpy as np 필요)

## numpy 배열을 생성하는 다양한 방법   
https://numpy.org/doc/stable/user/basics.creation.html


규모가 큰  배열의 경우 numpy에 내장된 함수를 사용하여 처음부터 배열을 생성한ㄴ 것이 더 효율적이다.   

기본 1차원 배열 생성 (열의 집합)

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

기본 2차원 배열 생성 (행열의 집합)

In [12]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.array([[2,3,4],
        [4,5,6],
        [6,7,8]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

0으로 채운 길이 10의 정수 배열 생성

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

1로 채운 3x5 부동 소수점 배열 생성

In [18]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3.14로 채운 3x5배열 생성

In [19]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### 선형, 수열로 채운 배열 생성

In [21]:
#0에서 시작해서 2씩 더해 20까지 채움(내장 함수 range()와 유사)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
#0과 1 사이에 일정한 간격을 가진 다섯개의 값을 채운 배열 생성

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
#균등하고 분포된 3x3 배열 생성(0~1 사이의 난수로 채움)

In [26]:
np.random.random((3,3))

array([[0.83467176, 0.86888867, 0.45293495],
       [0.13215554, 0.03236809, 0.83233333],
       [0.96449408, 0.43598803, 0.66771564]])

In [27]:
#매번 실행할때마다 import부터 시작해야함.

In [28]:
#정규분포 (평균=0, 표준편차=-1)의 난수로 채운 3x3 배열 생성

In [31]:
np.random.normal(0,1,(3,3))

array([[-1.32599527,  0.09514692,  1.29269107],
       [ 1.28045216,  1.19021193,  0.41804338],
       [-0.73171618, -0.496533  , -1.36320339]])

In [32]:
#[0,10]구간의 임의의 정수를 채운 3x3 배열 생성

In [33]:
np.random.randint(0,10,(3,3))

array([[5, 8, 9],
       [3, 7, 8],
       [4, 8, 5]])

In [34]:
#3x3 크기의 단위행렬 생성

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 세개의 정수를 가지는 초기화 되지 않은 배열 생성, 초기화 되는 값은 해당  메모리 위치에 이미 존재하고 있는 값(gabage 값)으로 채운다.

In [36]:
np.empty(3)

array([1., 1., 1.])

## numpy 표준 데이터 타입

https://numpy.org/doc/stable/user/basics.types.html   
numpy에서 사용하는 자료형 종류들

In [39]:
# numpy 배열은 한 가지 타입의 값을 담고 있으므로 해당 타입과 그 타입의 제약 사항을 자세히 알고 사용하는 것이 중요하다.
#배열을 구성할 때 데이터 타입은 문자열을 이용해 지정

In [41]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [43]:
#해당 데이터 타입과 관련된 numpy 객체를 사용해 지정

In [42]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# numpy 배열 사용

In [44]:
#파이썬에서도 데이터 처리는 numpy 배열 처리와 거의 비슷하다.
#pandas도 numpy 배열을 기반으로 작성되었다.

#### numpy 배열 기본조작

-배열 속성 지정   
배열의 크기, 모양, 메모리, 소비량, 데이터 타입을 결정한다.   
   
-배열 인덱싱
개별 배열 요소값을 가져오고 설정한다.   
   
-배열 슬라이싱   
큰 배열 내에 있는 작은 하위 배열을 가져오고 설정한다.  
   
-배열 재구조화   
해당 배열의 형상을 변경한다.   
   
-배열 결합 및 분할   
여러 배열을 하나로 결합하고 하나의 배열을 여러 개로 분할한다.   

배열 속성 지정: 배열의 크기, 모양, 메모리 소비량, 데이터 타입을 결정한다.

In [45]:
#numpy 사용->array 사용(속도가 빠르다.)

In [46]:
np.random.seed(0)

In [47]:
x1=np.random.randint(10, size=6) #1차원 배열
x2=np.random.randint(10, size=(3,4))#2차원 배열
x3=np.random.randint(10, size=(3,4,5))#3차원 배열

In [48]:
x1

array([5, 0, 3, 3, 7, 9])

In [49]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [50]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

-각 배열은 속성으로 ndim(차원의 개수), shape(각 차원의 크기), size(전체 배열의 크기)를 가지고 있다.

In [53]:
print('x1 ndim: ', x1.ndim) #차원의 개수
print('x1 shape: ', x1.shape) #차원의 크기
print('x1 size: ', x1.size) #전체 배열의 크기

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6


In [56]:
print('x2 ndim: ', x2.ndim) #차원의 개수
print('x2 shape: ', x2.shape) #차원의 크기
print('x2 size: ', x2.size) #전체 배열의 크기

x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12


In [57]:
print('x3 ndim: ', x3.ndim) #차원의 개수
print('x3 shape: ', x3.shape) #차원의 크기
print('x3 size: ', x3.size) #전체 배열의 크기

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [58]:
#object.속성(상태값=attribute=변수)<-행위에 따라서 변화가 이루어진다.
#object.메소드(행위=method=함수)

In [59]:
print('x1 dtype: ', x1.dtype) #배열이 type
print('x2 dtype: ', x2.dtype)
print('x3 dtype: ', x3.dtype)

x1 dtype:  int32
x2 dtype:  int32
x3 dtype:  int32


-itemsize: 각 배열 요소의 크기를 바이트 단위로 표시.   
-nbytes: 배열 전체 크기를 바이트 단위로 표시. itemsize를 size로 곱한 값과 동일.

In [62]:
print('x1 itemsize: ', x1.itemsize, 'bytes')
print('x1 nbyte : ', x1.nbytes, 'bytes')
print('x2 itemsize: ', x2.itemsize, 'bytes')
print('x2 nbyte : ', x2.nbytes, 'bytes')
print('x3 itemsize: ', x3.itemsize, 'bytes')
print('x3 nbyte : ', x3.nbytes, 'bytes')

x1 itemsize:  4 bytes
x1 nbyte :  24 bytes
x2 itemsize:  4 bytes
x2 nbyte :  48 bytes
x3 itemsize:  4 bytes
x3 nbyte :  240 bytes


In [63]:
#배열 요소 하나의 크기. x1의 경우, 4바이트짜리가 6개라서 24바이트. x2는 요소수가 12개, 12x4=48. x3는 20개짜리가 3개 모임. 
#itemsize는 기억구간 하나의 크기를 표시. size는 

#### 배열 인덱싱: 배열 요소에 접근하기

#### https://numpy.org/doc/stable/user/basics.indexing.html

In [64]:
x1

array([5, 0, 3, 3, 7, 9])

In [65]:
x1[0]

5

In [66]:
x1[4]

7

In [67]:
x1[-1] #배열을 뒤에서부터 인덱싱하려면 음수 인덱스 사용.

9

In [68]:
x1[-2]

7

In [70]:
#다 차원 배열에서는 .로 구분된 인덱스 튜플을 이용해 배열항목에 접근할 수 있다.

In [71]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [72]:
x2[0,0]

3

In [73]:
x2[2,0]

1

In [74]:
x2[2,-1]

7

-인덱스 표기법을 사용하여 요소의 값을 수정할 수도 있다.

In [75]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

-파이썬 list와 달리 numpy배열은 고정 타입을 가진다는 점을 명심하자.   
-예로 정수 배열에 부동 소수점 값을 기억시키면 그 값은 소수점 이하를 잘라버리고 저장한다.  

In [76]:
x1[0]=3.141592
x1

array([3, 0, 3, 3, 7, 9])

### 배열 슬라이싱: 하위 배열에 접근하기

-[]사용해 개별 배열 요소에 접근할 수 있는 것처럼 : 기호로 표시되는 슬라이스(slice)표기법으로 하위 배열에 접근할 수 있다.   
-numpy 슬라이싱 구문은 표준 파이썬 리스트의 슬라이싱 구문을 따른다.  
-배열 x의 슬라이스에 접근하려면 다음 구문을 사용한다.   
x[start : stop : step]   
-이 중 하나라도 지정되지 않으면 기본적으로 start=0, stop=배열차원의 크기, step=1로 값이 설정된다.   

In [79]:
#1차원 하위 배열
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
x[5]

5

In [81]:
x[5:]

array([5, 6, 7, 8, 9])

In [83]:
x[4:7]

array([4, 5, 6])

In [84]:
x[::2]

array([0, 2, 4, 6, 8])

In [85]:
x[1::2]

array([1, 3, 5, 7, 9])

-step값을 음수로 부여했을 때 혼동이 올 수 있다. 이 경우에는 start와 stop의 기본값이 서로 바뀐다.   
-이는 배열을 거꾸로 만드는 편리한 방법이 될 수 있다.   

In [86]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [87]:
x[5::-2]

array([5, 3, 1])

In [88]:
#다차원 배열 슬라이싱
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [89]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [90]:
x2[:3,::2] #[2]라는 뜻.

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [91]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [92]:
#뒤집고, 뒤집어서.

### 배열의 행과 열에 접근

-한 가지 공통으로 필요한 루틴은 배열의 단일 행이나 열에 접근하는 것이다.   
-이것은 단일 콜론으로 표시된 빈 슬라이스를 사용해 인덱싱과 슬라이싱을 결합하므로써 할 수 있다.

In [97]:
print(x2[:,0])

[12  7  1]


In [96]:
print(x2[0, : ])

[12  5  2  4]


행에 접근하는 경우 더 간결한 구문을 위해 빈 슬라이스를 생략할 수 있다.

In [98]:
print(x2[0]) #x2[0,:]와 동일.

[12  5  2  4]


### 사본이 아닌 뷰로서의 하위 배열

-배열 슬라이스가 배열 데이터의 사본(copy)이 아니라 뷰(view)를 반환한다는 점.   
-이는 numpy 배열 슬라이싱이 파이썬 리스트 슬라이싱과 다른 점으로 주의할 점.   
-파이썬 리스트에서 슬라이스는 사본이다.   

In [99]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [100]:
x2_sub=x2[:2,:2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [101]:
x2_sub[0,0]=99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [102]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [103]:
#12였는데 99로 바뀜. 즉 직접 바꾼 것이 아니라 x2_sub의 0,0을 바꾼 것.

-위와 같은 동작은 실제로 매우 유용하다.   
-이것은 매우 큰 빅데이터 세트를 다룰 때 기반 데이터 버퍼를 복사하지 않아도 이 데이터의 일부에 접근하고 처리할 수 있다는 뜻이다. 즉 만행 만열짜리 데이터가 있을 경우, 부분적으로 잘라내서 작업하면서 원본 내용을 바꾸는 것도 가능하다. 이걸 피하고 싶다면 copy를 써서 원본에 변화를 주지 않게 하는 방법이 있다.   
-view는 원본에 영향을 미침. 원본과 연결되어 있기 때문에. 슬라이싱해서 부분적으로 잘라와도 마찬가지. 반면 copy는 원본 데이터에 변화를 주지 않음. 원본과는 별개로 독립적으로 가져온 것이니까.      

### 배열 사본 만들기

-배열 뷰의 기능이 유용해도 때로는 배열이나 하위 배열 내의 데이터를 명시적으로 복사하는 것이 더 유용할 때가 있다.   
-copy()메서드를 이용하여 배열 명시적 복사를 수행할 수 있다.

In [105]:
x2_sub_copy=x2[:2,:2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [106]:
x2_sub_copy[0,0]=42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [107]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [108]:
#얘는 카피라서 내용이 안바뀐 것. 뷰는 바뀌지만.
#내가 뷰 하면 슬라이싱해서 잘라내는 것. 즉 원본에 영향을 미침. 원본에 영향을 미치고 싶지 않다면 copy 메서드를 써야한다.

### 배열 재구조화

배열의 형상을 변경하는 것이다.   
reshape()메서드를 사용한다.

In [110]:
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

-위 코드 동작시 초기 배열의 규모가 형상이 변경된 배열의 규모와 일치해야 한다.   
-reshape()메서드가 초기 배열의 사본(copy)이 아닌 뷰(view)을 사용하겠지만, 연속되지 않은 메모리 퍼버일 경우에는 그렇지 않을 수도 있다.   
-또 다른 일반적인 재구조화 패턴은 1차원 배열을 2차원 행이나 열 매트릭스로 전환하는 것이다.   
-이 작업은 reshape() 메서드로 할 수 있으며, 그렇지 않으면 슬라이스 연산 내에 newaxis 키워드를 사용할 수도 있다.

In [112]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [113]:
x.reshape((1,3))#reshape를 이용한 행 벡터로 재구조화

array([[1, 2, 3]])

In [114]:
x[np.newaxis,:]#newaxis를 이용한 행 벡터로 재구조화

array([[1, 2, 3]])

In [115]:
x.reshape((3,1)) #reshape를 이용한 열 벡터로 재구조화

array([[1],
       [2],
       [3]])

In [116]:
x[:, np.newaxis] #newaxis를 이용한 열 벡터로 재구조화

array([[1],
       [2],
       [3]])

### numpy 배열 연산: 유니버설 합수(universal function, ufuncs)

-numpy는 데이터 배열을 사용하여 최적화된 연산을 쉽고 유연한 인터페이스를 제공   
-numpy 배열의 연산은 아주 빠르거나 아주 느릴 수 있다.   
-이 연산을 빠르게 만드는 핵심은 벡터화(vetorized) 연산을 사용하는 것이다.   
-일반적으로 numpy의 유니버설 함수(universal function, ufuncs)를 통해 구현   
-배열 요소에 대한 반복적인 계산을 효율적으로 수행하게 해준다.   

-벡터화 연산은 간단히 배열에 연산을 수행해 각 요소에 적용함으로써 수행할 수 있다.   
-numpy에서 벡터화 연산은 numpy 배열의 값에 반복된 연산을 빠르게 수행하는 것을 주 목적으로 하는 ufuncs를 통해 구현   
-ufuncs는 스칼라(값)와 배열 사이의 연산 및 두 배열 간의 연산도 가능하다.   
-#스칼라(값), 벡터(array)

In [117]:
x=np.arange(4)
x

array([0, 1, 2, 3])

In [120]:
print('x    = ', x)
print('x+5    = ', x+5)
print('x-5    = ', x-5)
print('x*5    = ', x*5)
print('x/5    = ', x/5)
print('x//2    = ', x//2)
print('-x    = ', -x)
print('x**2    = ', x**2)
print('x%2    = ', x%2)

x    =  [0 1 2 3]
x+5    =  [5 6 7 8]
x-5    =  [-5 -4 -3 -2]
x*5    =  [ 0  5 10 15]
x/5    =  [0.  0.2 0.4 0.6]
x//2    =  [0 0 1 1]
-x    =  [ 0 -1 -2 -3]
x**2    =  [0 1 4 9]
x%2    =  [0 1 0 1]


#### 집계

-배열을 특정 연산으로 축소하고자 할 때 사용하는 메서드: reduce()   
-reduce() 메서드는 결과가 하나만 남을 때까지 해당 연산을 배열 요소에 반복해서 적용한다.   

In [121]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [122]:
np.add.reduce(x)

15

In [123]:
np.multiply.reduce(x)

120

-계산 중간 결과를 모두 저장하고 싶다면 accumulate() 메서드를 사용

In [124]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [125]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [126]:
#accumulate 함수를 쓰면 중간 과정을 보여줌.
#numpy는 자료 구성이 list와는 다르게 자료형이 하나라서 계산이 빠르다.

In [127]:
a=np.random.random(100)
a

array([0.65279032, 0.63505887, 0.99529957, 0.58185033, 0.41436859,
       0.4746975 , 0.6235101 , 0.33800761, 0.67475232, 0.31720174,
       0.77834548, 0.94957105, 0.66252687, 0.01357164, 0.6228461 ,
       0.67365963, 0.971945  , 0.87819347, 0.50962438, 0.05571469,
       0.45115921, 0.01998767, 0.44171092, 0.97958673, 0.35944446,
       0.48089353, 0.68866118, 0.88047589, 0.91823547, 0.21682214,
       0.56518887, 0.86510256, 0.50896896, 0.91672295, 0.92115761,
       0.08311249, 0.27771856, 0.0093567 , 0.84234208, 0.64717414,
       0.84138612, 0.26473016, 0.39782075, 0.55282148, 0.16494046,
       0.36980809, 0.14644176, 0.56961841, 0.70373728, 0.28847644,
       0.43328806, 0.75610669, 0.39609828, 0.89603839, 0.63892108,
       0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191,
       0.7670237 , 0.41182014, 0.67543908, 0.24979628, 0.31321833,
       0.96541622, 0.58846509, 0.65966841, 0.53320625, 0.23053302,
       0.39486929, 0.61880856, 0.47486752, 0.47013219, 0.71607

In [128]:
# 파이썬 내장 함수
sum(a)

52.12818058833704

In [129]:
# numpy 함수
np.sum(a)

52.12818058833702

In [130]:
#파이썬 내장 함수
min(a), max(a)

(0.009356704856532616, 0.9952995676778876)

In [131]:
#numpy 함수
np.min(a), np.max(a)

(0.009356704856532616, 0.9952995676778876)

In [132]:
a.sum(), a.min(), a.max()

(52.12818058833702, 0.009356704856532616, 0.9952995676778876)

message   
--------------   
a.sum()-------------->객체 지향 방식   
a는 object, sum은 method   

np.sum(a)->구조적(기능적 방식)   
----- --    
함수  인수   

다차원 배열은 집계 연사 수행 시 행이나 열을 기준으로 집계한다.

In [135]:
M=np.random.random((3,4))
M

array([[0.16684751, 0.77905102, 0.8649333 , 0.41139672],
       [0.13997259, 0.03322239, 0.98257496, 0.37329075],
       [0.42007537, 0.05058812, 0.36549611, 0.01662797]])

In [136]:
M.sum()

4.604076798225436

In [137]:
M.sum(axis=0)

array([0.72689547, 0.86286152, 2.21300436, 0.80131545])

In [138]:
M.sum(axis=1)

array([2.22222855, 1.52906068, 0.85278756])

-다차원 집계 함수는 어느 축(axis)을 지정하느냐에 따라 집계할 축을 결정할 수 있다.   
-axis 키워드는 축소할 배열의 차원을 지정한다. 즉 축을 결정한다.   
aixs=0은 열을 지정.
aixs=1은 행을 지정.

In [139]:
M.min(axis=0) #열에 대한 최소값

array([0.13997259, 0.03322239, 0.36549611, 0.01662797])

In [140]:
M.min(axis=1) #행에 대한 최소값

array([0.16684751, 0.03322239, 0.01662797])

nan: 결측치. nan 안전모드는 결측치 제거한다는 뜻.

In [ ]:
#214~236